apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-mysql-instance
  namespace: default
spec:
  serviceClassName: azure-mysqldb
  planName: basic50
  parameters:
    location: eastus
    resourceGroup: demo
