apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: jz-mysql-instance
  namespace: default
spec:
  serviceClassName: azure-mysqldb
  planName: basic50
  parameters:
    resourceGroup: demo
    serverName: jz-mysql # must be globally unique
    location: eastus
    skuName: MYSQLB50
    skuCapacityDTU: 50
    skuTier: Basic
    skuSizeMB: 51200
