apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-postgresql-instance
  namespace: default
spec:
  serviceClassName: azure-postgresqldb
  planName: basic50
  parameters:
    location: eastus
    resourceGroup: demo
