apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-redis-instance
  namespace: default
spec:
  serviceClassName: azure-rediscache
  planName: basic
  parameters:
    location: eastus
    resourceGroup: demo
