language: generic
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
services:
- docker
- docker-compose
sudo: required
script:
- make lint verify-vendored-code test docker-build
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    repo: deis/azure-service-broker
    all_branches: true
