language: generic
cache:
  directories:
  - .glide
services:
- docker
- docker-compose
sudo: required
before_script:
- make dev-bootstrap
script:
- make lint test docker-build
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    repo: deis/azure-service-broker
    all_branches: true
