version: 2
jobs:
  verify-vendored-code:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Verify Vendored Code
          command: make verify-vendored-code
  build:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Build Binary & Docker Image
          command: make docker-build
  test-unit:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Run Unit Tests
          command: make test-unit
  test-module-lifecycles:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Run Module Lifecycle Tests
          command: make test-module-lifecycles
  lint:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Run Lint
          command: make lint
  deploy:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Deploy to Docker Hub
          command: ./scripts/deploy.circle.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-unit
      - test-module-lifecycles
      - lint
      - verify-vendored-code
      # Deploy Docker images to Docker Hub
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
            - test-unit
            - test-module-lifecycles
            - lint
            - verify-vendored-code
