version: 2
jobs:
  lint:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Run Lint
          command: make lint
  verify-vendored-code:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Verify Vendored Code
          command: make verify-vendored-code
  test-unit:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Run Unit Tests
          command: make test-unit
  build:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Build Binary & Docker Image
          command: make docker-build
  test-module-lifecycles:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Run Module Lifecycle Tests
          command: make test-module-lifecycles
  deploy:
    working_directory: ~/go/src/github.com/Azure/azure-service-broker
    environment:
      GOPATH: ~/go
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./scripts/install-deps.sh
      - run:
          name: Deploy to Docker Hub
          command: ./scripts/deploy.dockerhub.sh
      - run:
          name: Deploy to Quay
          command: ./scripts/deploy.quay.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore: master
      - lint:
          requires:
            - hold
      - verify-vendored-code:
          requires:
            - hold
      - test-unit:
          requires:
            - hold
      - build:
          requires:
            - hold
      - test-module-lifecycles:
          requires:
            - hold
            - lint
            - verify-vendored-code
            - test-unit
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hold
            - lint
            - verify-vendored-code
            - test-unit
            - build
            - test-module-lifecycles
